/* ======================================================
   GUEST LIST — Wedding invitation data + autocomplete
   ====================================================== */
const GUEST_LIST = [
  // ── Family Groups ──────────────────────────────────────

  {
    id: 'england-parents',
    display: 'Mr and Mrs England',
    members: ['Deidre', 'Frank'],
    headCount: 2,
  },
  {
    id: 'campos-parents',
    display: 'Mr Cipriano Campos & Mrs Rosario Huambachano',
    members: ['Cipriano Campos', 'Rosario Huambachano'],
    headCount: 2,
  },
  {
    id: 'campos-chavez-family',
    display: 'The Campos Chavez Family',
    members: ['Raul Campos', 'Claudia Chavez', 'Leonardo Campos Chavez'],
    headCount: 3,
  },
  {
    id: 'huambachano-herrera',
    display: 'Mr and Mrs Huambachano Herrera',
    members: ['Orlando', 'Fatima'],
    headCount: 2,
  },
  {
    id: 'huambachano-alcantara-family',
    display: 'The Huambachano Alcantara Family',
    members: ['David', 'Isabel', 'Diana', 'Carlos', 'Jose Andres'],
    headCount: 5,
  },
  {
    id: 'huambachano-aguilar',
    display: 'Mr and Mrs Huambachano Aguilar',
    members: ['Pablo', 'Elvira'],
    headCount: 2,
  },
  {
    id: 'barba-valencia',
    display: 'Mr and Mrs Barba Valencia',
    members: ['Victor Barba', 'Patricia Valencia'],
    headCount: 2,
  },
  {
    id: 'close-ray-cate',
    display: 'Mr and Mrs Close',
    members: ['Ray', 'Cate'],
    headCount: 2,
  },
  {
    id: 'scarborough',
    display: 'Mr and Mrs Scarborough',
    members: ['Jeanmarie', 'Jeremiah'],
    headCount: 2,
  },
  {
    id: 'close-sean-family',
    display: 'The Close Family',
    members: ['Sean', 'Tara', 'Sean Jr'],
    headCount: 3,
  },
  {
    id: 'maurer-family',
    display: 'The Maurer Family',
    members: ['Brianna', 'Tiff', 'Remi', 'Callihan'],
    headCount: 4,
  },
  {
    id: 'montoya-family',
    display: 'The Montoya Family',
    members: ['Jose', 'Michele', 'Gabriella', 'Brandon'],
    headCount: 4,
  },
  {
    id: 'wall',
    display: 'Mr and Mrs Wall',
    members: ['Ryan', 'Dani'],
    headCount: 2,
  },
  {
    id: 'whitacre-family',
    display: 'The Whitacre Family',
    members: ['Mackenzie', 'Adam', 'Larkin'],
    headCount: 3,
  },
  {
    id: 'estrella-family',
    display: 'The Estrella Family',
    members: ['Alyssa', 'Kelvin', 'Kiara'],
    headCount: 3,
  },
  {
    id: 'ezagui',
    display: 'Mr and Mrs Ezagui',
    members: ['Cathy', 'Pete'],
    headCount: 2,
  },
  {
    id: 'miller',
    display: 'Mr and Mrs Miller',
    members: ['Dean', 'Denise'],
    headCount: 2,
  },
  {
    id: 'jacobs',
    display: 'Mr and Mrs Jacobs',
    members: ['Paige', 'Clay'],
    headCount: 2,
  },
  {
    id: 'mullin',
    display: 'Mr and Mrs Mullin',
    members: ['Amanda', 'Chad'],
    headCount: 2,
  },
  {
    id: 'gund',
    display: 'Mr and Mrs Gund',
    members: ['Melissa', 'Brandon'],
    headCount: 2,
  },
  {
    id: 'johnson-krista',
    display: 'Mr and Mrs Johnson',
    members: ['Krista', 'Travis'],
    headCount: 2,
  },
  {
    id: 'kane-presier',
    display: 'Ms Jessica Kane & Mr Jake Presier',
    members: ['Jessica Kane', 'Jake Presier'],
    headCount: 2,
  },
  {
    id: 'decker',
    display: 'Mr and Mrs Decker',
    members: ['Lisa', 'Matt'],
    headCount: 2,
  },
  {
    id: 'blum-misuraca',
    display: 'Mrs Denise Blum & Mrs Amanda Misuraca',
    members: ['Denise Blum', 'Amanda Misuraca'],
    headCount: 2,
  },
  {
    id: 'flores-montoya-family',
    display: 'The Flores Montoya Family',
    members: ['Fabi', 'Danny', 'Camila', 'Bellanie', 'Luciana', 'Aria'],
    headCount: 6,
  },
  {
    id: 'montoya-huambachano',
    display: 'Mr and Mrs Montoya Huambachano',
    members: ['Amilia', 'Willy'],
    headCount: 2,
  },
  {
    id: 'montoya-dasha-willy',
    display: 'Mr and Mrs Montoya',
    members: ['Dasha', 'Willy'],
    headCount: 2,
  },
  {
    id: 'sorrentino-family',
    display: 'The Sorrentino Family',
    members: ['Kiara', 'Ben', 'Andrew'],
    headCount: 3,
  },
  {
    id: 'rebaza-petrera',
    display: 'Ms Melissa Rebaza & Ms Talia Petrera & Guest',
    members: ['Melissa Rebaza', 'Talia Petrera'],
    headCount: 3,
    plusOne: true,
  },
  {
    id: 'deleo',
    display: 'Mr and Mrs Deleo',
    members: ['Linda', 'Joe'],
    headCount: 2,
  },

  // ── Individuals ────────────────────────────────────────

  {
    id: 'elizabeth-arcaya',
    display: 'Ms Elizabeth Arcaya',
    members: ['Elizabeth Arcaya'],
    headCount: 1,
  },
  {
    id: 'cameron-england',
    display: 'Ms Cameron England',
    members: ['Cameron England'],
    headCount: 1,
  },
  {
    id: 'eric-mininni',
    display: 'Mr Eric Mininni',
    members: ['Eric Mininni'],
    headCount: 1,
  },
  {
    id: 'rafael-campos',
    display: 'Mr Rafael Campos Huambachano',
    members: ['Rafael Campos Huambachano'],
    headCount: 1,
  },
  {
    id: 'joyce-close',
    display: 'Mrs Joyce Close',
    members: ['Joyce Close'],
    headCount: 1,
  },
  {
    id: 'jeanne-england',
    display: 'Mrs Jeanne England',
    members: ['Jeanne England'],
    headCount: 1,
  },
  {
    id: 'juliana-close',
    display: 'Ms Juliana Close',
    members: ['Juliana Close'],
    headCount: 1,
  },
  {
    id: 'madelyn-close',
    display: 'Ms Madelyn Close',
    members: ['Madelyn Close'],
    headCount: 1,
  },
  {
    id: 'raymond-close',
    display: 'Mr Raymond Close',
    members: ['Raymond Close'],
    headCount: 1,
  },
  {
    id: 'brendan-close',
    display: 'Mr Brendan Close',
    members: ['Brendan Close'],
    headCount: 1,
  },
  {
    id: 'alonso-huambachano',
    display: 'Mr Alonso Huambachano Herrera',
    members: ['Alonso Huambachano Herrera'],
    headCount: 1,
  },
  {
    id: 'carlos-raul-huambachano',
    display: 'Mr Carlos Raul Huambachano Herrera',
    members: ['Carlos Raul Huambachano Herrera'],
    headCount: 1,
  },
  {
    id: 'camille-rebando',
    display: 'Mrs Camille Rebando',
    members: ['Camille Rebando'],
    headCount: 1,
  },
  {
    id: 'crystal-letosky',
    display: 'Ms Crystal Letosky',
    members: ['Crystal Letosky'],
    headCount: 1,
  },
  {
    id: 'adrianna-poulmentis',
    display: 'Ms Adrianna Poulmentis',
    members: ['Adrianna Poulmentis'],
    headCount: 1,
  },
  {
    id: 'shannon-kogel',
    display: 'Ms Shannon Kogel',
    members: ['Shannon Kogel'],
    headCount: 1,
  },
  {
    id: 'tatiana-bengi',
    display: 'Ms Tatiana Bengi',
    members: ['Tatiana Bengi'],
    headCount: 1,
  },
  {
    id: 'purvi-gandhi',
    display: 'Ms Purvi Gandhi',
    members: ['Purvi Gandhi'],
    headCount: 1,
  },
  {
    id: 'jen-beldy-post',
    display: 'Ms Jen Beldy Post',
    members: ['Jen Beldy Post'],
    headCount: 1,
  },
  {
    id: 'jennifer-budke',
    display: 'Ms Jennifer Budke',
    members: ['Jennifer Budke'],
    headCount: 1,
  },
  {
    id: 'orlando-palomino',
    display: 'Mr Orlando Palomino',
    members: ['Orlando Palomino'],
    headCount: 1,
  },
  {
    id: 'jenny-wang',
    display: 'Ms Jenny Wang',
    members: ['Jenny Wang'],
    headCount: 1,
  },
  {
    id: 'justine-murphy',
    display: 'Ms Justine Murphy',
    members: ['Justine Murphy'],
    headCount: 1,
  },
  {
    id: 'melanie-hoffmann',
    display: 'Ms Melanie Hoffmann',
    members: ['Melanie Hoffmann'],
    headCount: 1,
  },
  {
    id: 'paula-park',
    display: 'Ms Paula Park',
    members: ['Paula Park'],
    headCount: 1,
  },
  {
    id: 'liz-stanton',
    display: 'Ms Liz Stanton',
    members: ['Liz Stanton'],
    headCount: 1,
  },
  {
    id: 'leslie-smith',
    display: 'Ms Leslie Smith',
    members: ['Leslie Smith'],
    headCount: 1,
  },
  {
    id: 'sasha-vilfort',
    display: 'Ms Sasha Vilfort',
    members: ['Sasha Vilfort'],
    headCount: 1,
  },
  {
    id: 'lillian-molina',
    display: 'Ms Lillian Molina',
    members: ['Lillian Molina'],
    headCount: 1,
  },
  {
    id: 'anissa-deu-pree',
    display: 'Ms Anissa Deu Pree',
    members: ['Anissa Deu Pree'],
    headCount: 1,
  },
  {
    id: 'tyra-gardner',
    display: 'Ms Tyra Gardner',
    members: ['Tyra Gardner'],
    headCount: 1,
  },
  {
    id: 'jeanette-mcgraw',
    display: 'Mrs Jeanette McGraw',
    members: ['Jeanette McGraw'],
    headCount: 1,
  },
  {
    id: 'mirtha-rodriguez',
    display: 'Ms Mirtha Rodriguez',
    members: ['Mirtha Rodriguez'],
    headCount: 1,
  },
  {
    id: 'alyson-miller',
    display: 'Ms Alyson Miller',
    members: ['Alyson Miller'],
    headCount: 1,
  },
  {
    id: 'margaret-power',
    display: 'Ms Margaret Power',
    members: ['Margaret Power'],
    headCount: 1,
  },
  {
    id: 'adrienne-pepe',
    display: 'Ms Adrienne Pepe',
    members: ['Adrienne Pepe'],
    headCount: 1,
  },
  {
    id: 'denise-maiden',
    display: 'Ms Denise Maiden',
    members: ['Denise Maiden'],
    headCount: 1,
  },
  {
    id: 'jessica-gauthier',
    display: 'Ms Jessica Gauthier',
    members: ['Jessica Gauthier'],
    headCount: 1,
  },
  {
    id: 'ellen-lanaia',
    display: 'Ms Ellen Lanaia',
    members: ['Ellen Lanaia'],
    headCount: 1,
  },
  {
    id: 'kevin-johnson',
    display: 'Mr Kevin Johnson',
    members: ['Kevin Johnson'],
    headCount: 1,
  },
  {
    id: 'claudia-saint-gerard',
    display: 'Ms Claudia Saint Gerard',
    members: ['Claudia Saint Gerard'],
    headCount: 1,
  },
  {
    id: 'justine-padilla',
    display: 'Ms Justine Padilla',
    members: ['Justine Padilla'],
    headCount: 1,
  },
  {
    id: 'gab-candela',
    display: 'Ms Gab Candela',
    members: ['Gab Candela'],
    headCount: 1,
  },
  {
    id: 'tori-kammer',
    display: 'Ms Tori Kammer',
    members: ['Tori Kammer'],
    headCount: 1,
  },
  {
    id: 'dalia-vargas',
    display: 'Ms Dalia Vargas',
    members: ['Dalia Vargas'],
    headCount: 1,
  },

  // ── Plus-One Entries ───────────────────────────────────

  {
    id: 'bowie-johnson',
    display: 'Mr Bowie Johnson & Guest',
    members: ['Bowie Johnson'],
    headCount: 2,
    plusOne: true,
  },
  {
    id: 'emma-hopley',
    display: 'Ms Emma Hopley & Guest',
    members: ['Emma Hopley'],
    headCount: 2,
    plusOne: true,
  },
  {
    id: 'nicola-hopley',
    display: 'Ms Nicola Hopley & Guest',
    members: ['Nicola Hopley'],
    headCount: 2,
    plusOne: true,
  },
  {
    id: 'tyler-chatel',
    display: 'Mr Tyler Chatel & Guest',
    members: ['Tyler Chatel'],
    headCount: 2,
    plusOne: true,
  },
  {
    id: 'jorge-torres',
    display: 'Mr Jorge Torres & Guest',
    members: ['Jorge Torres'],
    headCount: 2,
    plusOne: true,
  },
  {
    id: 'sandra-torres',
    display: 'Ms Sandra Torres & Son',
    members: ['Sandra Torres'],
    headCount: 2,
    plusOne: true,
  },
  {
    id: 'eric-krull',
    display: 'Mr Eric Krull & Guest',
    members: ['Eric Krull'],
    headCount: 2,
    plusOne: true,
  },
  {
    id: 'barry-egan',
    display: 'Mr Barry Egan & Guest',
    members: ['Barry Egan'],
    headCount: 2,
    plusOne: true,
  },
  {
    id: 'gina-goldsmith',
    display: 'Ms Gina Goldsmith & Guest',
    members: ['Gina Goldsmith'],
    headCount: 2,
    plusOne: true,
  },
];
