/* ======================================================
   GUEST LIST — Wedding invitation data + code lookup
   ====================================================== */
const GUEST_LIST = [
  // ── Family Groups ──────────────────────────────────────

  {
    id: 'england-parents',
    display: 'Mr and Mrs England',
    members: ['Deidre', 'Frank'],
    headCount: 2,
    code: '1001',
  },
  {
    id: 'cipriano-campos',
    display: 'Mr Cipriano Campos',
    members: ['Cipriano Campos'],
    headCount: 1,
    code: '1002',
  },
  {
    id: 'rosario-huambachano',
    display: 'Mrs Rosario Huambachano',
    members: ['Rosario Huambachano'],
    headCount: 1,
    code: '1003',
  },
  {
    id: 'campos-chavez-family',
    display: 'The Campos Chavez Family',
    members: ['Raul Campos', 'Claudia Chavez', 'Leonardo Campos Chavez'],
    headCount: 3,
    code: '1004',
  },
  {
    id: 'huambachano-herrera',
    display: 'Mr and Mrs Huambachano Herrera',
    members: ['Orlando', 'Fatima'],
    headCount: 2,
    code: '1005',
  },
  {
    id: 'huambachano-alcantara-family',
    display: 'The Huambachano Alcantara Family',
    members: ['David', 'Isabel', 'Diana', 'Carlos', 'Jose Andres'],
    headCount: 5,
    code: '1006',
  },
  {
    id: 'huambachano-aguilar',
    display: 'Mr and Mrs Huambachano Aguilar',
    members: ['Pablo', 'Elvira'],
    headCount: 2,
    code: '1007',
  },
  {
    id: 'barba-valencia',
    display: 'Mr and Mrs Barba Valencia',
    members: ['Victor Barba', 'Patricia Valencia'],
    headCount: 2,
    code: '1008',
  },
  {
    id: 'close-ray-cate',
    display: 'Mr and Mrs Close',
    members: ['Ray', 'Cate'],
    headCount: 2,
    code: '1009',
  },
  {
    id: 'scarborough',
    display: 'Mr and Mrs Scarborough',
    members: ['Jeanmarie', 'Jeremiah'],
    headCount: 2,
    code: '1010',
  },
  {
    id: 'close-sean-family',
    display: 'The Close Family',
    members: ['Sean', 'Tara', 'Sean Jr'],
    headCount: 3,
    code: '1011',
  },
  {
    id: 'maurer-family',
    display: 'The Maurer Family',
    members: ['Brianna', 'Tiff', 'Remi', 'Callihan'],
    headCount: 4,
    code: '1012',
  },
  {
    id: 'montoya-family',
    display: 'The Montoya Family',
    members: ['Jose', 'Michele', 'Gabriella', 'Brandon'],
    headCount: 4,
    code: '1013',
  },
  {
    id: 'wall',
    display: 'Mr and Mrs Wall',
    members: ['Ryan', 'Dani'],
    headCount: 2,
    code: '1014',
  },
  {
    id: 'whitacre-family',
    display: 'The Whitacre Family',
    members: ['Mackenzie', 'Adam', 'Larkin'],
    headCount: 3,
    code: '1015',
  },
  {
    id: 'estrella-family',
    display: 'The Estrella Family',
    members: ['Alyssa', 'Kelvin', 'Kiara'],
    headCount: 3,
    code: '1016',
  },
  {
    id: 'jacobs',
    display: 'Mr and Mrs Jacobs',
    members: ['Paige', 'Clay'],
    headCount: 2,
    code: '1017',
  },
  {
    id: 'miller',
    display: 'Mr and Mrs Miller',
    members: ['Dean', 'Denise'],
    headCount: 2,
    code: '1018',
  },
  {
    id: 'mullin',
    display: 'Mr and Mrs Mullin',
    members: ['Amanda', 'Chad'],
    headCount: 2,
    code: '1019',
  },
  {
    id: 'gund',
    display: 'Mr and Mrs Gund',
    members: ['Melissa', 'Brandon'],
    headCount: 2,
    code: '1020',
  },
  {
    id: 'johnson-krista',
    display: 'Mr and Mrs Johnson',
    members: ['Krista', 'Travis'],
    headCount: 2,
    code: '1021',
  },
  {
    id: 'decker',
    display: 'Mr and Mrs Decker',
    members: ['Lisa', 'Matt'],
    headCount: 2,
    code: '1022',
  },
  {
    id: 'blum-misuraca',
    display: 'Mrs Denise Blum & Mrs Amanda Misuraca',
    members: ['Denise Blum', 'Amanda Misuraca'],
    headCount: 2,
    code: '1023',
  },
  {
    id: 'flores-montoya-family',
    display: 'The Flores Montoya Family',
    members: ['Fabi', 'Danny', 'Camila', 'Bellanie', 'Luciana', 'Aria'],
    headCount: 6,
    code: '1024',
  },
  {
    id: 'montoya-huambachano',
    display: 'Mr and Mrs Montoya Huambachano',
    members: ['Amilia', 'Willy'],
    headCount: 2,
    code: '1025',
  },
  {
    id: 'montoya-dasha-willy',
    display: 'Mr and Mrs Montoya',
    members: ['Dasha', 'Willy'],
    headCount: 2,
    code: '1026',
  },
  {
    id: 'sorrentino-family',
    display: 'The Sorrentino Family',
    members: ['Kiara', 'Ben', 'Andrew'],
    headCount: 3,
    code: '1027',
  },
  {
    id: 'deleo',
    display: 'Mr and Mrs Deleo',
    members: ['Linda', 'Joe'],
    headCount: 2,
    code: '1028',
  },
  {
    id: 'mahoney',
    display: 'Mr and Mrs Mahoney',
    members: ['Sue', 'Steve'],
    headCount: 2,
    code: '1029',
  },
  {
    id: 'tyler-chatel-salazar',
    display: 'Mr Tyler Chatel and Ms Vanessa Salazar',
    members: ['Tyler Chatel', 'Vanessa Salazar'],
    headCount: 2,
    code: '1030',
  },
  {
    id: 'kane-presier',
    display: 'Ms Jessica Kane & Mr Jake Presier',
    members: ['Jessica Kane', 'Jake Presier'],
    headCount: 2,
    code: '1031',
  },

  // ── Individuals ────────────────────────────────────────

  {
    id: 'carol-miller',
    display: 'Mrs Carol Miller',
    members: ['Carol Miller'],
    headCount: 1,
    code: '1032',
  },
  {
    id: 'diane-staiano',
    display: 'Mrs Diane Staiano',
    members: ['Diane Staiano'],
    headCount: 1,
    code: '1033',
  },
  {
    id: 'melissa-rebaza',
    display: 'Ms Melissa Rebaza',
    members: ['Melissa Rebaza'],
    headCount: 1,
    code: '1034',
  },
  {
    id: 'cameron-england',
    display: 'Ms Cameron England',
    members: ['Cameron England'],
    headCount: 1,
    code: '1035',
  },
  {
    id: 'eric-mininni',
    display: 'Mr Eric Mininni',
    members: ['Eric Mininni'],
    headCount: 1,
    code: '1036',
  },
  {
    id: 'rafael-campos',
    display: 'Mr Rafael Campos Huambachano',
    members: ['Rafael Campos Huambachano'],
    headCount: 1,
    code: '1037',
  },
  {
    id: 'joyce-close',
    display: 'Mrs Joyce Close',
    members: ['Joyce Close'],
    headCount: 1,
    code: '1038',
  },
  {
    id: 'jeanne-england',
    display: 'Mrs Jeanne England',
    members: ['Jeanne England'],
    headCount: 1,
    code: '1039',
  },
  {
    id: 'alonso-huambachano',
    display: 'Mr Alonso Huambachano Herrera',
    members: ['Alonso Huambachano Herrera'],
    headCount: 1,
    code: '1040',
  },
  {
    id: 'carlos-raul-huambachano',
    display: 'Mr Carlos Raul Huambachano Herrera',
    members: ['Carlos Raul Huambachano Herrera'],
    headCount: 1,
    code: '1041',
  },
  {
    id: 'juliana-close',
    display: 'Ms Juliana Close',
    members: ['Juliana Close'],
    headCount: 1,
    code: '1042',
  },
  {
    id: 'madelyn-close',
    display: 'Ms Madelyn Close',
    members: ['Madelyn Close'],
    headCount: 1,
    code: '1043',
  },
  {
    id: 'raymond-close',
    display: 'Mr Raymond Close',
    members: ['Raymond Close'],
    headCount: 1,
    code: '1044',
  },
  {
    id: 'brendan-close',
    display: 'Mr Brendan Close',
    members: ['Brendan Close'],
    headCount: 1,
    code: '1045',
  },
  {
    id: 'elizabeth-arcaya',
    display: 'Ms Elizabeth Arcaya',
    members: ['Elizabeth Arcaya'],
    headCount: 1,
    code: '1046',
  },
  {
    id: 'camille-rebando',
    display: 'Mrs Camille Rebando',
    members: ['Camille Rebando'],
    headCount: 1,
    code: '1047',
  },
  {
    id: 'crystal-letosky',
    display: 'Ms Crystal Letosky',
    members: ['Crystal Letosky'],
    headCount: 1,
    code: '1048',
  },
  {
    id: 'adrianna-poulmentis',
    display: 'Ms Adrianna Poulmentis',
    members: ['Adrianna Poulmentis'],
    headCount: 1,
    code: '1049',
  },
  {
    id: 'shannon-kogel',
    display: 'Ms Shannon Kogel',
    members: ['Shannon Kogel'],
    headCount: 1,
    code: '1050',
  },
  {
    id: 'tatiana-bengi',
    display: 'Ms Tatiana Bengi',
    members: ['Tatiana Bengi'],
    headCount: 1,
    code: '1051',
  },
  {
    id: 'purvi-gandhi',
    display: 'Ms Purvi Gandhi',
    members: ['Purvi Gandhi'],
    headCount: 1,
    code: '1052',
  },
  {
    id: 'jen-beldy-post',
    display: 'Ms Jen Beldy Post',
    members: ['Jen Beldy Post'],
    headCount: 1,
    code: '1053',
  },
  {
    id: 'jennifer-budke',
    display: 'Ms Jennifer Budke',
    members: ['Jennifer Budke'],
    headCount: 1,
    code: '1054',
  },
  {
    id: 'orlando-palomino',
    display: 'Mr Orlando Palomino',
    members: ['Orlando Palomino'],
    headCount: 1,
    code: '1055',
  },
  {
    id: 'jenny-wang',
    display: 'Ms Jenny Wang',
    members: ['Jenny Wang'],
    headCount: 1,
    code: '1056',
  },
  {
    id: 'justine-murphy',
    display: 'Ms Justine Murphy',
    members: ['Justine Murphy'],
    headCount: 1,
    code: '1057',
  },
  {
    id: 'melanie-hoffmann',
    display: 'Ms Melanie Hoffmann',
    members: ['Melanie Hoffmann'],
    headCount: 1,
    code: '1058',
  },
  {
    id: 'paula-park',
    display: 'Ms Paula Park',
    members: ['Paula Park'],
    headCount: 1,
    code: '1059',
  },
  {
    id: 'liz-stanton',
    display: 'Ms Liz Stanton',
    members: ['Liz Stanton'],
    headCount: 1,
    code: '1060',
  },
  {
    id: 'leslie-smith',
    display: 'Ms Leslie Smith',
    members: ['Leslie Smith'],
    headCount: 1,
    code: '1061',
  },
  {
    id: 'sasha-vilfort',
    display: 'Ms Sasha Vilfort',
    members: ['Sasha Vilfort'],
    headCount: 1,
    code: '1062',
  },
  {
    id: 'lillian-molina',
    display: 'Ms Lillian Molina',
    members: ['Lillian Molina'],
    headCount: 1,
    code: '1063',
  },
  {
    id: 'anissa-deu-pree',
    display: 'Ms Anissa Deu Pree',
    members: ['Anissa Deu Pree'],
    headCount: 1,
    code: '1064',
  },
  {
    id: 'tyra-gardner',
    display: 'Ms Tyra Gardner',
    members: ['Tyra Gardner'],
    headCount: 1,
    code: '1065',
  },
  {
    id: 'jeanette-mcgraw',
    display: 'Mrs Jeanette McGraw',
    members: ['Jeanette McGraw'],
    headCount: 1,
    code: '1066',
  },
  {
    id: 'sandra-torres',
    display: 'Ms Sandra Torres & Son',
    members: ['Sandra Torres'],
    headCount: 2,
    plusOne: true,
    code: '1067',
  },
  {
    id: 'mirtha-rodriguez',
    display: 'Ms Mirtha Rodriguez',
    members: ['Mirtha Rodriguez'],
    headCount: 1,
    code: '1068',
  },
  {
    id: 'alyson-miller',
    display: 'Ms Alyson Miller',
    members: ['Alyson Miller'],
    headCount: 1,
    code: '1069',
  },
  {
    id: 'margaret-power',
    display: 'Ms Margaret Power',
    members: ['Margaret Power'],
    headCount: 1,
    code: '1070',
  },
  {
    id: 'adrienne-pepe',
    display: 'Ms Adrienne Pepe',
    members: ['Adrienne Pepe'],
    headCount: 1,
    code: '1071',
  },
  {
    id: 'denise-maiden',
    display: 'Ms Denise Maiden',
    members: ['Denise Maiden'],
    headCount: 1,
    code: '1072',
  },
  {
    id: 'jessica-gauthier',
    display: 'Ms Jessica Gauthier',
    members: ['Jessica Gauthier'],
    headCount: 1,
    code: '1073',
  },
  {
    id: 'ellen-lanaia',
    display: 'Ms Ellen Lanaia',
    members: ['Ellen Lanaia'],
    headCount: 1,
    code: '1074',
  },
  {
    id: 'kevin-johnson',
    display: 'Mr Kevin Johnson',
    members: ['Kevin Johnson'],
    headCount: 1,
    code: '1075',
  },
  {
    id: 'claudia-saint-gerard',
    display: 'Ms Claudia Saint Gerard',
    members: ['Claudia Saint Gerard'],
    headCount: 1,
    code: '1076',
  },
  {
    id: 'justine-padilla',
    display: 'Ms Justine Padilla',
    members: ['Justine Padilla'],
    headCount: 1,
    code: '1077',
  },
  {
    id: 'gab-candela',
    display: 'Ms Gab Candela',
    members: ['Gab Candela'],
    headCount: 1,
    code: '1078',
  },
  {
    id: 'tori-kammer',
    display: 'Ms Tori Kammer',
    members: ['Tori Kammer'],
    headCount: 1,
    code: '1079',
  },
  {
    id: 'dalia-vargas',
    display: 'Ms Dalia Vargas',
    members: ['Dalia Vargas'],
    headCount: 1,
    code: '1080',
  },

  // ── Plus-One Entries ───────────────────────────────────

  {
    id: 'eric-krull',
    display: 'Mr Eric Krull & Guest',
    members: ['Eric Krull'],
    headCount: 2,
    plusOne: true,
    code: '1081',
  },
  {
    id: 'talia-petrera',
    display: 'Ms Talia Petrera & Guest',
    members: ['Talia Petrera'],
    headCount: 2,
    plusOne: true,
    code: '1082',
  },
  {
    id: 'bowie-johnson',
    display: 'Mr Bowie Johnson & Guest',
    members: ['Bowie Johnson'],
    headCount: 2,
    plusOne: true,
    code: '1083',
  },
  {
    id: 'emma-hopley',
    display: 'Ms Emma Hopley & Guest',
    members: ['Emma Hopley'],
    headCount: 2,
    plusOne: true,
    code: '1084',
  },
  {
    id: 'nicola-hopley',
    display: 'Ms Nicola Hopley & Guest',
    members: ['Nicola Hopley'],
    headCount: 2,
    plusOne: true,
    code: '1085',
  },
  {
    id: 'jorge-torres',
    display: 'Mr Jorge Torres & Guest',
    members: ['Jorge Torres'],
    headCount: 2,
    plusOne: true,
    code: '1086',
  },
  {
    id: 'gina-goldsmith',
    display: 'Ms Gina Goldsmith & Guest',
    members: ['Gina Goldsmith'],
    headCount: 2,
    plusOne: true,
    code: '1087',
  },
  {
    id: 'barry-egan',
    display: 'Mr Barry Egan & Guest',
    members: ['Barry Egan'],
    headCount: 2,
    plusOne: true,
    code: '1088',
  },
];

// ── Lookup helper ────────────────────────────────────────
function findGuestByCode(code) {
  return GUEST_LIST.find(g => g.code === code.trim().toUpperCase()) || null;
}
